export const locationHelper = {
  countries: ["Canada", "United States"],
  country_states: {
    Canada: [
      "Ontario",
      "Quebec",
      "British Columbia",
      "Alberta",
      "Manitoba",
      "Nova Scotia",
      "Saskatchewan",
      "Newfoundland and Labrador",
      "New Brunswick",
      "Prince Edward Island",
      "Yukon",
      "Northwest Territories",
      "Nunavut",
    ],
    "United States": [
      "New York",
      "California",
      "Illinois",
      "Florida",
      "Texas",
      "Pennsylvania",
      "Georgia",
      "District of Columbia",
      "Massachusetts",
      "Arizona",
      "Michigan",
      "Washington",
      "Minnesota",
      "Colorado",
      "Maryland",
      "Nevada",
      "Missouri",
      "Oregon",
      "Ohio",
      "Indiana",
      "North Carolina",
      "Virginia",
      "Wisconsin",
      "Rhode Island",
      "Utah",
      "Tennessee",
      "Kentucky",
      "Oklahoma",
      "Connecticut",
      "Louisiana",
      "Hawaii",
      "Nebraska",
      "New Mexico",
      "Alabama",
      "South Carolina",
      "Iowa",
      "Kansas",
      "Arkansas",
      "Idaho",
      "Mississippi",
      "New Jersey",
      "Alaska",
      "New Hampshire",
      "Maine",
      "North Dakota",
      "West Virginia",
      "South Dakota",
      "Delaware",
      "Montana",
      "Vermont",
      "Wyoming",
    ],
  },
};
